Updated repo-update script

diff --git a/repo-update b/repo-update
--- a/repo-update
+++ b/repo-update
@@ -3,13 +3,21 @@
 repoDir='/home/neil/dotfiles/'
 cd "$repoDir"
 
-blurb=$(git pull)
+status=$(git status -uno)
+echo "$status" | grep -i 'up-to-date' &> /dev/null
 
-echo "$blurb" | grep -i error
-E="$?"
-echo "$blurb" | grep -i fatal
-F="$?"
+if (( $? != 0 )); then
+	blurb=$(git pull)
 
-if (( $E == 0 )) || (( $F ==0 )); then
-	echo "$blurb"
+	echo "$blurb" | grep -i error
+	E="$?"
+	echo "$blurb" | grep -i fatal
+	F="$?"
+
+	if (( $E == 0 )) || (( $F ==0 )); then
+		echo "$blurb"
+		notify-send 'Failed to pull updates to dotfiles'
+	else
+		notify-send 'Pulled updates to dotfiles'
+	fi
 fi
